# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Function.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x46unction.proto\">\n\x12\x46unctionAddRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05index\x18\x02 \x01(\r\x12\x0b\n\x03\x65lf\x18\x03 \x01(\x0c\"\x8d\x01\n\x10\x46unctionAddReply\x12\x33\n\x06status\x18\x01 \x01(\x0e\x32#.FunctionAddReply.FunctionAddStatus\"D\n\x11\x46unctionAddStatus\x12\x06\n\x02OK\x10\x00\x12\x11\n\rINVALID_STAGE\x10\x01\x12\x14\n\x10INVALID_FUNCTION\x10\x02\"&\n\x15\x46unctionRemoveRequest\x12\r\n\x05index\x18\x01 \x01(\r\"\x83\x01\n\x13\x46unctionRemoveReply\x12\x39\n\x06status\x18\x01 \x01(\x0e\x32).FunctionRemoveReply.FunctionRemoveStatus\"1\n\x14\x46unctionRemoveStatus\x12\x06\n\x02OK\x10\x00\x12\x11\n\rINVALID_STAGE\x10\x01\"A\n\x11\x46unctionListEntry\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05index\x18\x02 \x01(\r\x12\x0f\n\x07\x63ounter\x18\x03 \x01(\x04\"\x15\n\x13\x46unctionListRequest\"8\n\x11\x46unctionListReply\x12#\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x12.FunctionListEntryb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Function_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FUNCTIONADDREQUEST._serialized_start=18
  _FUNCTIONADDREQUEST._serialized_end=80
  _FUNCTIONADDREPLY._serialized_start=83
  _FUNCTIONADDREPLY._serialized_end=224
  _FUNCTIONADDREPLY_FUNCTIONADDSTATUS._serialized_start=156
  _FUNCTIONADDREPLY_FUNCTIONADDSTATUS._serialized_end=224
  _FUNCTIONREMOVEREQUEST._serialized_start=226
  _FUNCTIONREMOVEREQUEST._serialized_end=264
  _FUNCTIONREMOVEREPLY._serialized_start=267
  _FUNCTIONREMOVEREPLY._serialized_end=398
  _FUNCTIONREMOVEREPLY_FUNCTIONREMOVESTATUS._serialized_start=349
  _FUNCTIONREMOVEREPLY_FUNCTIONREMOVESTATUS._serialized_end=398
  _FUNCTIONLISTENTRY._serialized_start=400
  _FUNCTIONLISTENTRY._serialized_end=465
  _FUNCTIONLISTREQUEST._serialized_start=467
  _FUNCTIONLISTREQUEST._serialized_end=488
  _FUNCTIONLISTREPLY._serialized_start=490
  _FUNCTIONLISTREPLY._serialized_end=546
# @@protoc_insertion_point(module_scope)
