# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Header.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cHeader.proto\"\xf7\x03\n\x06Header\"\xec\x03\n\x04Type\x12\t\n\x05HELLO\x10\x00\x12\x18\n\x14\x46UNCTION_ADD_REQUEST\x10\x01\x12\x16\n\x12\x46UNCTION_ADD_REPLY\x10\x02\x12\x1b\n\x17\x46UNCTION_REMOVE_REQUEST\x10\x03\x12\x19\n\x15\x46UNCTION_REMOVE_REPLY\x10\x04\x12\x19\n\x15\x46UNCTION_LIST_REQUEST\x10\x05\x12\x17\n\x13\x46UNCTION_LIST_REPLY\x10\x06\x12\x17\n\x13TABLES_LIST_REQUEST\x10\x07\x12\x15\n\x11TABLES_LIST_REPLY\x10\x08\x12\x16\n\x12TABLE_LIST_REQUEST\x10\t\x12\x14\n\x10TABLE_LIST_REPLY\x10\n\x12\x1b\n\x17TABLE_ENTRY_GET_REQUEST\x10\x0b\x12\x19\n\x15TABLE_ENTRY_GET_REPLY\x10\x0c\x12\x1e\n\x1aTABLE_ENTRY_INSERT_REQUEST\x10\r\x12\x1c\n\x18TABLE_ENTRY_INSERT_REPLY\x10\x0e\x12\x1e\n\x1aTABLE_ENTRY_DELETE_REQUEST\x10\x0f\x12\x1c\n\x18TABLE_ENTRY_DELETE_REPLY\x10\x10\x12\r\n\tPACKET_IN\x10\x11\x12\x0e\n\nPACKET_OUT\x10\x12\x12\n\n\x06NOTIFY\x10\x13\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Header_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HEADER._serialized_start=17
  _HEADER._serialized_end=520
  _HEADER_TYPE._serialized_start=28
  _HEADER_TYPE._serialized_end=520
# @@protoc_insertion_point(module_scope)
