/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Function.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "Function.pb-c.h"
void   function_add_request__init
                     (FunctionAddRequest         *message)
{
  static const FunctionAddRequest init_value = FUNCTION_ADD_REQUEST__INIT;
  *message = init_value;
}
size_t function_add_request__get_packed_size
                     (const FunctionAddRequest *message)
{
  assert(message->base.descriptor == &function_add_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t function_add_request__pack
                     (const FunctionAddRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &function_add_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t function_add_request__pack_to_buffer
                     (const FunctionAddRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &function_add_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FunctionAddRequest *
       function_add_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FunctionAddRequest *)
     protobuf_c_message_unpack (&function_add_request__descriptor,
                                allocator, len, data);
}
void   function_add_request__free_unpacked
                     (FunctionAddRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &function_add_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   function_add_reply__init
                     (FunctionAddReply         *message)
{
  static const FunctionAddReply init_value = FUNCTION_ADD_REPLY__INIT;
  *message = init_value;
}
size_t function_add_reply__get_packed_size
                     (const FunctionAddReply *message)
{
  assert(message->base.descriptor == &function_add_reply__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t function_add_reply__pack
                     (const FunctionAddReply *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &function_add_reply__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t function_add_reply__pack_to_buffer
                     (const FunctionAddReply *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &function_add_reply__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FunctionAddReply *
       function_add_reply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FunctionAddReply *)
     protobuf_c_message_unpack (&function_add_reply__descriptor,
                                allocator, len, data);
}
void   function_add_reply__free_unpacked
                     (FunctionAddReply *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &function_add_reply__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   function_remove_request__init
                     (FunctionRemoveRequest         *message)
{
  static const FunctionRemoveRequest init_value = FUNCTION_REMOVE_REQUEST__INIT;
  *message = init_value;
}
size_t function_remove_request__get_packed_size
                     (const FunctionRemoveRequest *message)
{
  assert(message->base.descriptor == &function_remove_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t function_remove_request__pack
                     (const FunctionRemoveRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &function_remove_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t function_remove_request__pack_to_buffer
                     (const FunctionRemoveRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &function_remove_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FunctionRemoveRequest *
       function_remove_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FunctionRemoveRequest *)
     protobuf_c_message_unpack (&function_remove_request__descriptor,
                                allocator, len, data);
}
void   function_remove_request__free_unpacked
                     (FunctionRemoveRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &function_remove_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   function_remove_reply__init
                     (FunctionRemoveReply         *message)
{
  static const FunctionRemoveReply init_value = FUNCTION_REMOVE_REPLY__INIT;
  *message = init_value;
}
size_t function_remove_reply__get_packed_size
                     (const FunctionRemoveReply *message)
{
  assert(message->base.descriptor == &function_remove_reply__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t function_remove_reply__pack
                     (const FunctionRemoveReply *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &function_remove_reply__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t function_remove_reply__pack_to_buffer
                     (const FunctionRemoveReply *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &function_remove_reply__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FunctionRemoveReply *
       function_remove_reply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FunctionRemoveReply *)
     protobuf_c_message_unpack (&function_remove_reply__descriptor,
                                allocator, len, data);
}
void   function_remove_reply__free_unpacked
                     (FunctionRemoveReply *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &function_remove_reply__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   function_list_entry__init
                     (FunctionListEntry         *message)
{
  static const FunctionListEntry init_value = FUNCTION_LIST_ENTRY__INIT;
  *message = init_value;
}
size_t function_list_entry__get_packed_size
                     (const FunctionListEntry *message)
{
  assert(message->base.descriptor == &function_list_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t function_list_entry__pack
                     (const FunctionListEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &function_list_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t function_list_entry__pack_to_buffer
                     (const FunctionListEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &function_list_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FunctionListEntry *
       function_list_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FunctionListEntry *)
     protobuf_c_message_unpack (&function_list_entry__descriptor,
                                allocator, len, data);
}
void   function_list_entry__free_unpacked
                     (FunctionListEntry *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &function_list_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   function_list_request__init
                     (FunctionListRequest         *message)
{
  static const FunctionListRequest init_value = FUNCTION_LIST_REQUEST__INIT;
  *message = init_value;
}
size_t function_list_request__get_packed_size
                     (const FunctionListRequest *message)
{
  assert(message->base.descriptor == &function_list_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t function_list_request__pack
                     (const FunctionListRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &function_list_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t function_list_request__pack_to_buffer
                     (const FunctionListRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &function_list_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FunctionListRequest *
       function_list_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FunctionListRequest *)
     protobuf_c_message_unpack (&function_list_request__descriptor,
                                allocator, len, data);
}
void   function_list_request__free_unpacked
                     (FunctionListRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &function_list_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   function_list_reply__init
                     (FunctionListReply         *message)
{
  static const FunctionListReply init_value = FUNCTION_LIST_REPLY__INIT;
  *message = init_value;
}
size_t function_list_reply__get_packed_size
                     (const FunctionListReply *message)
{
  assert(message->base.descriptor == &function_list_reply__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t function_list_reply__pack
                     (const FunctionListReply *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &function_list_reply__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t function_list_reply__pack_to_buffer
                     (const FunctionListReply *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &function_list_reply__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FunctionListReply *
       function_list_reply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FunctionListReply *)
     protobuf_c_message_unpack (&function_list_reply__descriptor,
                                allocator, len, data);
}
void   function_list_reply__free_unpacked
                     (FunctionListReply *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &function_list_reply__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor function_add_request__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(FunctionAddRequest, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "index",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(FunctionAddRequest, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "elf",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(FunctionAddRequest, elf),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned function_add_request__field_indices_by_name[] = {
  2,   /* field[2] = elf */
  1,   /* field[1] = index */
  0,   /* field[0] = name */
};
static const ProtobufCIntRange function_add_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor function_add_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FunctionAddRequest",
  "FunctionAddRequest",
  "FunctionAddRequest",
  "",
  sizeof(FunctionAddRequest),
  3,
  function_add_request__field_descriptors,
  function_add_request__field_indices_by_name,
  1,  function_add_request__number_ranges,
  (ProtobufCMessageInit) function_add_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue function_add_reply__function_add_status__enum_values_by_number[3] =
{
  { "OK", "FUNCTION_ADD_REPLY__FUNCTION_ADD_STATUS__OK", 0 },
  { "INVALID_STAGE", "FUNCTION_ADD_REPLY__FUNCTION_ADD_STATUS__INVALID_STAGE", 1 },
  { "INVALID_FUNCTION", "FUNCTION_ADD_REPLY__FUNCTION_ADD_STATUS__INVALID_FUNCTION", 2 },
};
static const ProtobufCIntRange function_add_reply__function_add_status__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex function_add_reply__function_add_status__enum_values_by_name[3] =
{
  { "INVALID_FUNCTION", 2 },
  { "INVALID_STAGE", 1 },
  { "OK", 0 },
};
const ProtobufCEnumDescriptor function_add_reply__function_add_status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "FunctionAddReply.FunctionAddStatus",
  "FunctionAddStatus",
  "FunctionAddReply__FunctionAddStatus",
  "",
  3,
  function_add_reply__function_add_status__enum_values_by_number,
  3,
  function_add_reply__function_add_status__enum_values_by_name,
  1,
  function_add_reply__function_add_status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor function_add_reply__field_descriptors[1] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(FunctionAddReply, status),
    &function_add_reply__function_add_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned function_add_reply__field_indices_by_name[] = {
  0,   /* field[0] = status */
};
static const ProtobufCIntRange function_add_reply__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor function_add_reply__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FunctionAddReply",
  "FunctionAddReply",
  "FunctionAddReply",
  "",
  sizeof(FunctionAddReply),
  1,
  function_add_reply__field_descriptors,
  function_add_reply__field_indices_by_name,
  1,  function_add_reply__number_ranges,
  (ProtobufCMessageInit) function_add_reply__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor function_remove_request__field_descriptors[1] =
{
  {
    "index",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(FunctionRemoveRequest, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned function_remove_request__field_indices_by_name[] = {
  0,   /* field[0] = index */
};
static const ProtobufCIntRange function_remove_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor function_remove_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FunctionRemoveRequest",
  "FunctionRemoveRequest",
  "FunctionRemoveRequest",
  "",
  sizeof(FunctionRemoveRequest),
  1,
  function_remove_request__field_descriptors,
  function_remove_request__field_indices_by_name,
  1,  function_remove_request__number_ranges,
  (ProtobufCMessageInit) function_remove_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue function_remove_reply__function_remove_status__enum_values_by_number[2] =
{
  { "OK", "FUNCTION_REMOVE_REPLY__FUNCTION_REMOVE_STATUS__OK", 0 },
  { "INVALID_STAGE", "FUNCTION_REMOVE_REPLY__FUNCTION_REMOVE_STATUS__INVALID_STAGE", 1 },
};
static const ProtobufCIntRange function_remove_reply__function_remove_status__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex function_remove_reply__function_remove_status__enum_values_by_name[2] =
{
  { "INVALID_STAGE", 1 },
  { "OK", 0 },
};
const ProtobufCEnumDescriptor function_remove_reply__function_remove_status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "FunctionRemoveReply.FunctionRemoveStatus",
  "FunctionRemoveStatus",
  "FunctionRemoveReply__FunctionRemoveStatus",
  "",
  2,
  function_remove_reply__function_remove_status__enum_values_by_number,
  2,
  function_remove_reply__function_remove_status__enum_values_by_name,
  1,
  function_remove_reply__function_remove_status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor function_remove_reply__field_descriptors[1] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(FunctionRemoveReply, status),
    &function_remove_reply__function_remove_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned function_remove_reply__field_indices_by_name[] = {
  0,   /* field[0] = status */
};
static const ProtobufCIntRange function_remove_reply__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor function_remove_reply__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FunctionRemoveReply",
  "FunctionRemoveReply",
  "FunctionRemoveReply",
  "",
  sizeof(FunctionRemoveReply),
  1,
  function_remove_reply__field_descriptors,
  function_remove_reply__field_indices_by_name,
  1,  function_remove_reply__number_ranges,
  (ProtobufCMessageInit) function_remove_reply__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor function_list_entry__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(FunctionListEntry, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "index",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(FunctionListEntry, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "counter",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(FunctionListEntry, counter),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned function_list_entry__field_indices_by_name[] = {
  2,   /* field[2] = counter */
  1,   /* field[1] = index */
  0,   /* field[0] = name */
};
static const ProtobufCIntRange function_list_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor function_list_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FunctionListEntry",
  "FunctionListEntry",
  "FunctionListEntry",
  "",
  sizeof(FunctionListEntry),
  3,
  function_list_entry__field_descriptors,
  function_list_entry__field_indices_by_name,
  1,  function_list_entry__number_ranges,
  (ProtobufCMessageInit) function_list_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define function_list_request__field_descriptors NULL
#define function_list_request__field_indices_by_name NULL
#define function_list_request__number_ranges NULL
const ProtobufCMessageDescriptor function_list_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FunctionListRequest",
  "FunctionListRequest",
  "FunctionListRequest",
  "",
  sizeof(FunctionListRequest),
  0,
  function_list_request__field_descriptors,
  function_list_request__field_indices_by_name,
  0,  function_list_request__number_ranges,
  (ProtobufCMessageInit) function_list_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor function_list_reply__field_descriptors[1] =
{
  {
    "entries",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(FunctionListReply, n_entries),
    offsetof(FunctionListReply, entries),
    &function_list_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned function_list_reply__field_indices_by_name[] = {
  0,   /* field[0] = entries */
};
static const ProtobufCIntRange function_list_reply__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor function_list_reply__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FunctionListReply",
  "FunctionListReply",
  "FunctionListReply",
  "",
  sizeof(FunctionListReply),
  1,
  function_list_reply__field_descriptors,
  function_list_reply__field_indices_by_name,
  1,  function_list_reply__number_ranges,
  (ProtobufCMessageInit) function_list_reply__init,
  NULL,NULL,NULL    /* reserved[123] */
};
