/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Header.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "Header.pb-c.h"
void   header__init
                     (Header         *message)
{
  static const Header init_value = HEADER__INIT;
  *message = init_value;
}
size_t header__get_packed_size
                     (const Header *message)
{
  assert(message->base.descriptor == &header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t header__pack
                     (const Header *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t header__pack_to_buffer
                     (const Header *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Header *
       header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Header *)
     protobuf_c_message_unpack (&header__descriptor,
                                allocator, len, data);
}
void   header__free_unpacked
                     (Header *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue header__type__enum_values_by_number[20] =
{
  { "HELLO", "HEADER__TYPE__HELLO", 0 },
  { "FUNCTION_ADD_REQUEST", "HEADER__TYPE__FUNCTION_ADD_REQUEST", 1 },
  { "FUNCTION_ADD_REPLY", "HEADER__TYPE__FUNCTION_ADD_REPLY", 2 },
  { "FUNCTION_REMOVE_REQUEST", "HEADER__TYPE__FUNCTION_REMOVE_REQUEST", 3 },
  { "FUNCTION_REMOVE_REPLY", "HEADER__TYPE__FUNCTION_REMOVE_REPLY", 4 },
  { "FUNCTION_LIST_REQUEST", "HEADER__TYPE__FUNCTION_LIST_REQUEST", 5 },
  { "FUNCTION_LIST_REPLY", "HEADER__TYPE__FUNCTION_LIST_REPLY", 6 },
  { "TABLES_LIST_REQUEST", "HEADER__TYPE__TABLES_LIST_REQUEST", 7 },
  { "TABLES_LIST_REPLY", "HEADER__TYPE__TABLES_LIST_REPLY", 8 },
  { "TABLE_LIST_REQUEST", "HEADER__TYPE__TABLE_LIST_REQUEST", 9 },
  { "TABLE_LIST_REPLY", "HEADER__TYPE__TABLE_LIST_REPLY", 10 },
  { "TABLE_ENTRY_GET_REQUEST", "HEADER__TYPE__TABLE_ENTRY_GET_REQUEST", 11 },
  { "TABLE_ENTRY_GET_REPLY", "HEADER__TYPE__TABLE_ENTRY_GET_REPLY", 12 },
  { "TABLE_ENTRY_INSERT_REQUEST", "HEADER__TYPE__TABLE_ENTRY_INSERT_REQUEST", 13 },
  { "TABLE_ENTRY_INSERT_REPLY", "HEADER__TYPE__TABLE_ENTRY_INSERT_REPLY", 14 },
  { "TABLE_ENTRY_DELETE_REQUEST", "HEADER__TYPE__TABLE_ENTRY_DELETE_REQUEST", 15 },
  { "TABLE_ENTRY_DELETE_REPLY", "HEADER__TYPE__TABLE_ENTRY_DELETE_REPLY", 16 },
  { "PACKET_IN", "HEADER__TYPE__PACKET_IN", 17 },
  { "PACKET_OUT", "HEADER__TYPE__PACKET_OUT", 18 },
  { "NOTIFY", "HEADER__TYPE__NOTIFY", 19 },
};
static const ProtobufCIntRange header__type__value_ranges[] = {
{0, 0},{0, 20}
};
static const ProtobufCEnumValueIndex header__type__enum_values_by_name[20] =
{
  { "FUNCTION_ADD_REPLY", 2 },
  { "FUNCTION_ADD_REQUEST", 1 },
  { "FUNCTION_LIST_REPLY", 6 },
  { "FUNCTION_LIST_REQUEST", 5 },
  { "FUNCTION_REMOVE_REPLY", 4 },
  { "FUNCTION_REMOVE_REQUEST", 3 },
  { "HELLO", 0 },
  { "NOTIFY", 19 },
  { "PACKET_IN", 17 },
  { "PACKET_OUT", 18 },
  { "TABLES_LIST_REPLY", 8 },
  { "TABLES_LIST_REQUEST", 7 },
  { "TABLE_ENTRY_DELETE_REPLY", 16 },
  { "TABLE_ENTRY_DELETE_REQUEST", 15 },
  { "TABLE_ENTRY_GET_REPLY", 12 },
  { "TABLE_ENTRY_GET_REQUEST", 11 },
  { "TABLE_ENTRY_INSERT_REPLY", 14 },
  { "TABLE_ENTRY_INSERT_REQUEST", 13 },
  { "TABLE_LIST_REPLY", 10 },
  { "TABLE_LIST_REQUEST", 9 },
};
const ProtobufCEnumDescriptor header__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Header.Type",
  "Type",
  "Header__Type",
  "",
  20,
  header__type__enum_values_by_number,
  20,
  header__type__enum_values_by_name,
  1,
  header__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
#define header__field_descriptors NULL
#define header__field_indices_by_name NULL
#define header__number_ranges NULL
const ProtobufCMessageDescriptor header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Header",
  "Header",
  "Header",
  "",
  sizeof(Header),
  0,
  header__field_descriptors,
  header__field_indices_by_name,
  0,  header__number_ranges,
  (ProtobufCMessageInit) header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
