/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Hello.proto */

#ifndef PROTOBUF_C_Hello_2eproto__INCLUDED
#define PROTOBUF_C_Hello_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Hello Hello;


/* --- enums --- */


/* --- messages --- */

struct  Hello
{
  ProtobufCMessage base;
  uint32_t version;
  uint64_t dpid;
};
#define HELLO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hello__descriptor) \
    , 0, 0 }


/* Hello methods */
void   hello__init
                     (Hello         *message);
size_t hello__get_packed_size
                     (const Hello   *message);
size_t hello__pack
                     (const Hello   *message,
                      uint8_t             *out);
size_t hello__pack_to_buffer
                     (const Hello   *message,
                      ProtobufCBuffer     *buffer);
Hello *
       hello__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hello__free_unpacked
                     (Hello *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Hello_Closure)
                 (const Hello *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor hello__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_Hello_2eproto__INCLUDED */
