/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Notify.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "Notify.pb-c.h"
void   notify__init
                     (Notify         *message)
{
  static const Notify init_value = NOTIFY__INIT;
  *message = init_value;
}
size_t notify__get_packed_size
                     (const Notify *message)
{
  assert(message->base.descriptor == &notify__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t notify__pack
                     (const Notify *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &notify__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t notify__pack_to_buffer
                     (const Notify *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &notify__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Notify *
       notify__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Notify *)
     protobuf_c_message_unpack (&notify__descriptor,
                                allocator, len, data);
}
void   notify__free_unpacked
                     (Notify *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &notify__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor notify__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Notify, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Notify, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned notify__field_indices_by_name[] = {
  1,   /* field[1] = data */
  0,   /* field[0] = id */
};
static const ProtobufCIntRange notify__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor notify__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Notify",
  "Notify",
  "Notify",
  "",
  sizeof(Notify),
  2,
  notify__field_descriptors,
  notify__field_indices_by_name,
  1,  notify__number_ranges,
  (ProtobufCMessageInit) notify__init,
  NULL,NULL,NULL    /* reserved[123] */
};
