/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Notify.proto */

#ifndef PROTOBUF_C_Notify_2eproto__INCLUDED
#define PROTOBUF_C_Notify_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Notify Notify;


/* --- enums --- */


/* --- messages --- */

struct  Notify
{
  ProtobufCMessage base;
  uint32_t id;
  ProtobufCBinaryData data;
};
#define NOTIFY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&notify__descriptor) \
    , 0, {0,NULL} }


/* Notify methods */
void   notify__init
                     (Notify         *message);
size_t notify__get_packed_size
                     (const Notify   *message);
size_t notify__pack
                     (const Notify   *message,
                      uint8_t             *out);
size_t notify__pack_to_buffer
                     (const Notify   *message,
                      ProtobufCBuffer     *buffer);
Notify *
       notify__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   notify__free_unpacked
                     (Notify *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Notify_Closure)
                 (const Notify *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor notify__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_Notify_2eproto__INCLUDED */
