/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Packet.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "Packet.pb-c.h"
void   packet_in__init
                     (PacketIn         *message)
{
  static const PacketIn init_value = PACKET_IN__INIT;
  *message = init_value;
}
size_t packet_in__get_packed_size
                     (const PacketIn *message)
{
  assert(message->base.descriptor == &packet_in__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t packet_in__pack
                     (const PacketIn *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &packet_in__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t packet_in__pack_to_buffer
                     (const PacketIn *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &packet_in__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PacketIn *
       packet_in__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PacketIn *)
     protobuf_c_message_unpack (&packet_in__descriptor,
                                allocator, len, data);
}
void   packet_in__free_unpacked
                     (PacketIn *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &packet_in__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   packet_out__init
                     (PacketOut         *message)
{
  static const PacketOut init_value = PACKET_OUT__INIT;
  *message = init_value;
}
size_t packet_out__get_packed_size
                     (const PacketOut *message)
{
  assert(message->base.descriptor == &packet_out__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t packet_out__pack
                     (const PacketOut *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &packet_out__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t packet_out__pack_to_buffer
                     (const PacketOut *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &packet_out__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PacketOut *
       packet_out__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PacketOut *)
     protobuf_c_message_unpack (&packet_out__descriptor,
                                allocator, len, data);
}
void   packet_out__free_unpacked
                     (PacketOut *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &packet_out__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor packet_in__field_descriptors[1] =
{
  {
    "data",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(PacketIn, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned packet_in__field_indices_by_name[] = {
  0,   /* field[0] = data */
};
static const ProtobufCIntRange packet_in__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor packet_in__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PacketIn",
  "PacketIn",
  "PacketIn",
  "",
  sizeof(PacketIn),
  1,
  packet_in__field_descriptors,
  packet_in__field_indices_by_name,
  1,  packet_in__number_ranges,
  (ProtobufCMessageInit) packet_in__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor packet_out__field_descriptors[2] =
{
  {
    "data",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(PacketOut, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "out_port",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(PacketOut, out_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned packet_out__field_indices_by_name[] = {
  0,   /* field[0] = data */
  1,   /* field[1] = out_port */
};
static const ProtobufCIntRange packet_out__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor packet_out__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PacketOut",
  "PacketOut",
  "PacketOut",
  "",
  sizeof(PacketOut),
  2,
  packet_out__field_descriptors,
  packet_out__field_indices_by_name,
  1,  packet_out__number_ranges,
  (ProtobufCMessageInit) packet_out__init,
  NULL,NULL,NULL    /* reserved[123] */
};
