/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Table.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "Table.pb-c.h"
void   table_definition__init
                     (TableDefinition         *message)
{
  static const TableDefinition init_value = TABLE_DEFINITION__INIT;
  *message = init_value;
}
size_t table_definition__get_packed_size
                     (const TableDefinition *message)
{
  assert(message->base.descriptor == &table_definition__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t table_definition__pack
                     (const TableDefinition *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &table_definition__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t table_definition__pack_to_buffer
                     (const TableDefinition *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &table_definition__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TableDefinition *
       table_definition__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TableDefinition *)
     protobuf_c_message_unpack (&table_definition__descriptor,
                                allocator, len, data);
}
void   table_definition__free_unpacked
                     (TableDefinition *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &table_definition__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tables_list_request__init
                     (TablesListRequest         *message)
{
  static const TablesListRequest init_value = TABLES_LIST_REQUEST__INIT;
  *message = init_value;
}
size_t tables_list_request__get_packed_size
                     (const TablesListRequest *message)
{
  assert(message->base.descriptor == &tables_list_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tables_list_request__pack
                     (const TablesListRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tables_list_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tables_list_request__pack_to_buffer
                     (const TablesListRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tables_list_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TablesListRequest *
       tables_list_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TablesListRequest *)
     protobuf_c_message_unpack (&tables_list_request__descriptor,
                                allocator, len, data);
}
void   tables_list_request__free_unpacked
                     (TablesListRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tables_list_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tables_list_reply__init
                     (TablesListReply         *message)
{
  static const TablesListReply init_value = TABLES_LIST_REPLY__INIT;
  *message = init_value;
}
size_t tables_list_reply__get_packed_size
                     (const TablesListReply *message)
{
  assert(message->base.descriptor == &tables_list_reply__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tables_list_reply__pack
                     (const TablesListReply *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tables_list_reply__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tables_list_reply__pack_to_buffer
                     (const TablesListReply *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tables_list_reply__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TablesListReply *
       tables_list_reply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TablesListReply *)
     protobuf_c_message_unpack (&tables_list_reply__descriptor,
                                allocator, len, data);
}
void   tables_list_reply__free_unpacked
                     (TablesListReply *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tables_list_reply__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   table_list_request__init
                     (TableListRequest         *message)
{
  static const TableListRequest init_value = TABLE_LIST_REQUEST__INIT;
  *message = init_value;
}
size_t table_list_request__get_packed_size
                     (const TableListRequest *message)
{
  assert(message->base.descriptor == &table_list_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t table_list_request__pack
                     (const TableListRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &table_list_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t table_list_request__pack_to_buffer
                     (const TableListRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &table_list_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TableListRequest *
       table_list_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TableListRequest *)
     protobuf_c_message_unpack (&table_list_request__descriptor,
                                allocator, len, data);
}
void   table_list_request__free_unpacked
                     (TableListRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &table_list_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   table_list_reply__init
                     (TableListReply         *message)
{
  static const TableListReply init_value = TABLE_LIST_REPLY__INIT;
  *message = init_value;
}
size_t table_list_reply__get_packed_size
                     (const TableListReply *message)
{
  assert(message->base.descriptor == &table_list_reply__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t table_list_reply__pack
                     (const TableListReply *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &table_list_reply__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t table_list_reply__pack_to_buffer
                     (const TableListReply *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &table_list_reply__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TableListReply *
       table_list_reply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TableListReply *)
     protobuf_c_message_unpack (&table_list_reply__descriptor,
                                allocator, len, data);
}
void   table_list_reply__free_unpacked
                     (TableListReply *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &table_list_reply__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   table_entry_get_request__init
                     (TableEntryGetRequest         *message)
{
  static const TableEntryGetRequest init_value = TABLE_ENTRY_GET_REQUEST__INIT;
  *message = init_value;
}
size_t table_entry_get_request__get_packed_size
                     (const TableEntryGetRequest *message)
{
  assert(message->base.descriptor == &table_entry_get_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t table_entry_get_request__pack
                     (const TableEntryGetRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &table_entry_get_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t table_entry_get_request__pack_to_buffer
                     (const TableEntryGetRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &table_entry_get_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TableEntryGetRequest *
       table_entry_get_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TableEntryGetRequest *)
     protobuf_c_message_unpack (&table_entry_get_request__descriptor,
                                allocator, len, data);
}
void   table_entry_get_request__free_unpacked
                     (TableEntryGetRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &table_entry_get_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   table_entry_get_reply__init
                     (TableEntryGetReply         *message)
{
  static const TableEntryGetReply init_value = TABLE_ENTRY_GET_REPLY__INIT;
  *message = init_value;
}
size_t table_entry_get_reply__get_packed_size
                     (const TableEntryGetReply *message)
{
  assert(message->base.descriptor == &table_entry_get_reply__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t table_entry_get_reply__pack
                     (const TableEntryGetReply *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &table_entry_get_reply__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t table_entry_get_reply__pack_to_buffer
                     (const TableEntryGetReply *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &table_entry_get_reply__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TableEntryGetReply *
       table_entry_get_reply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TableEntryGetReply *)
     protobuf_c_message_unpack (&table_entry_get_reply__descriptor,
                                allocator, len, data);
}
void   table_entry_get_reply__free_unpacked
                     (TableEntryGetReply *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &table_entry_get_reply__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   table_entry_insert_request__init
                     (TableEntryInsertRequest         *message)
{
  static const TableEntryInsertRequest init_value = TABLE_ENTRY_INSERT_REQUEST__INIT;
  *message = init_value;
}
size_t table_entry_insert_request__get_packed_size
                     (const TableEntryInsertRequest *message)
{
  assert(message->base.descriptor == &table_entry_insert_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t table_entry_insert_request__pack
                     (const TableEntryInsertRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &table_entry_insert_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t table_entry_insert_request__pack_to_buffer
                     (const TableEntryInsertRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &table_entry_insert_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TableEntryInsertRequest *
       table_entry_insert_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TableEntryInsertRequest *)
     protobuf_c_message_unpack (&table_entry_insert_request__descriptor,
                                allocator, len, data);
}
void   table_entry_insert_request__free_unpacked
                     (TableEntryInsertRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &table_entry_insert_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   table_entry_insert_reply__init
                     (TableEntryInsertReply         *message)
{
  static const TableEntryInsertReply init_value = TABLE_ENTRY_INSERT_REPLY__INIT;
  *message = init_value;
}
size_t table_entry_insert_reply__get_packed_size
                     (const TableEntryInsertReply *message)
{
  assert(message->base.descriptor == &table_entry_insert_reply__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t table_entry_insert_reply__pack
                     (const TableEntryInsertReply *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &table_entry_insert_reply__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t table_entry_insert_reply__pack_to_buffer
                     (const TableEntryInsertReply *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &table_entry_insert_reply__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TableEntryInsertReply *
       table_entry_insert_reply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TableEntryInsertReply *)
     protobuf_c_message_unpack (&table_entry_insert_reply__descriptor,
                                allocator, len, data);
}
void   table_entry_insert_reply__free_unpacked
                     (TableEntryInsertReply *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &table_entry_insert_reply__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   table_entry_delete_request__init
                     (TableEntryDeleteRequest         *message)
{
  static const TableEntryDeleteRequest init_value = TABLE_ENTRY_DELETE_REQUEST__INIT;
  *message = init_value;
}
size_t table_entry_delete_request__get_packed_size
                     (const TableEntryDeleteRequest *message)
{
  assert(message->base.descriptor == &table_entry_delete_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t table_entry_delete_request__pack
                     (const TableEntryDeleteRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &table_entry_delete_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t table_entry_delete_request__pack_to_buffer
                     (const TableEntryDeleteRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &table_entry_delete_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TableEntryDeleteRequest *
       table_entry_delete_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TableEntryDeleteRequest *)
     protobuf_c_message_unpack (&table_entry_delete_request__descriptor,
                                allocator, len, data);
}
void   table_entry_delete_request__free_unpacked
                     (TableEntryDeleteRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &table_entry_delete_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   table_entry_delete_reply__init
                     (TableEntryDeleteReply         *message)
{
  static const TableEntryDeleteReply init_value = TABLE_ENTRY_DELETE_REPLY__INIT;
  *message = init_value;
}
size_t table_entry_delete_reply__get_packed_size
                     (const TableEntryDeleteReply *message)
{
  assert(message->base.descriptor == &table_entry_delete_reply__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t table_entry_delete_reply__pack
                     (const TableEntryDeleteReply *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &table_entry_delete_reply__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t table_entry_delete_reply__pack_to_buffer
                     (const TableEntryDeleteReply *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &table_entry_delete_reply__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TableEntryDeleteReply *
       table_entry_delete_reply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TableEntryDeleteReply *)
     protobuf_c_message_unpack (&table_entry_delete_reply__descriptor,
                                allocator, len, data);
}
void   table_entry_delete_reply__free_unpacked
                     (TableEntryDeleteReply *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &table_entry_delete_reply__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue table_definition__table_type__enum_values_by_number[4] =
{
  { "UNSPEC", "TABLE_DEFINITION__TABLE_TYPE__UNSPEC", 0 },
  { "HASH", "TABLE_DEFINITION__TABLE_TYPE__HASH", 1 },
  { "ARRAY", "TABLE_DEFINITION__TABLE_TYPE__ARRAY", 2 },
  { "LPM_TRIE", "TABLE_DEFINITION__TABLE_TYPE__LPM_TRIE", 11 },
};
static const ProtobufCIntRange table_definition__table_type__value_ranges[] = {
{0, 0},{11, 3},{0, 4}
};
static const ProtobufCEnumValueIndex table_definition__table_type__enum_values_by_name[4] =
{
  { "ARRAY", 2 },
  { "HASH", 1 },
  { "LPM_TRIE", 3 },
  { "UNSPEC", 0 },
};
const ProtobufCEnumDescriptor table_definition__table_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "TableDefinition.TableType",
  "TableType",
  "TableDefinition__TableType",
  "",
  4,
  table_definition__table_type__enum_values_by_number,
  4,
  table_definition__table_type__enum_values_by_name,
  2,
  table_definition__table_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor table_definition__field_descriptors[5] =
{
  {
    "table_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TableDefinition, table_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "table_type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(TableDefinition, table_type),
    &table_definition__table_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key_size",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TableDefinition, key_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value_size",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TableDefinition, value_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_entries",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TableDefinition, max_entries),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned table_definition__field_indices_by_name[] = {
  2,   /* field[2] = key_size */
  4,   /* field[4] = max_entries */
  0,   /* field[0] = table_name */
  1,   /* field[1] = table_type */
  3,   /* field[3] = value_size */
};
static const ProtobufCIntRange table_definition__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor table_definition__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TableDefinition",
  "TableDefinition",
  "TableDefinition",
  "",
  sizeof(TableDefinition),
  5,
  table_definition__field_descriptors,
  table_definition__field_indices_by_name,
  1,  table_definition__number_ranges,
  (ProtobufCMessageInit) table_definition__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tables_list_request__field_descriptors[1] =
{
  {
    "index",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TablesListRequest, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tables_list_request__field_indices_by_name[] = {
  0,   /* field[0] = index */
};
static const ProtobufCIntRange tables_list_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor tables_list_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TablesListRequest",
  "TablesListRequest",
  "TablesListRequest",
  "",
  sizeof(TablesListRequest),
  1,
  tables_list_request__field_descriptors,
  tables_list_request__field_indices_by_name,
  1,  tables_list_request__number_ranges,
  (ProtobufCMessageInit) tables_list_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tables_list_reply__field_descriptors[2] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(TablesListReply, status),
    &table_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "entries",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TablesListReply, n_entries),
    offsetof(TablesListReply, entries),
    &table_definition__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tables_list_reply__field_indices_by_name[] = {
  1,   /* field[1] = entries */
  0,   /* field[0] = status */
};
static const ProtobufCIntRange tables_list_reply__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor tables_list_reply__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TablesListReply",
  "TablesListReply",
  "TablesListReply",
  "",
  sizeof(TablesListReply),
  2,
  tables_list_reply__field_descriptors,
  tables_list_reply__field_indices_by_name,
  1,  tables_list_reply__number_ranges,
  (ProtobufCMessageInit) tables_list_reply__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor table_list_request__field_descriptors[2] =
{
  {
    "index",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TableListRequest, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "table_name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TableListRequest, table_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned table_list_request__field_indices_by_name[] = {
  0,   /* field[0] = index */
  1,   /* field[1] = table_name */
};
static const ProtobufCIntRange table_list_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor table_list_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TableListRequest",
  "TableListRequest",
  "TableListRequest",
  "",
  sizeof(TableListRequest),
  2,
  table_list_request__field_descriptors,
  table_list_request__field_indices_by_name,
  1,  table_list_request__number_ranges,
  (ProtobufCMessageInit) table_list_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor table_list_reply__field_descriptors[4] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(TableListReply, status),
    &table_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "entry",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(TableListReply, entry),
    &table_definition__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n_items",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TableListReply, n_items),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "items",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(TableListReply, items),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned table_list_reply__field_indices_by_name[] = {
  1,   /* field[1] = entry */
  3,   /* field[3] = items */
  2,   /* field[2] = n_items */
  0,   /* field[0] = status */
};
static const ProtobufCIntRange table_list_reply__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor table_list_reply__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TableListReply",
  "TableListReply",
  "TableListReply",
  "",
  sizeof(TableListReply),
  4,
  table_list_reply__field_descriptors,
  table_list_reply__field_indices_by_name,
  1,  table_list_reply__number_ranges,
  (ProtobufCMessageInit) table_list_reply__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor table_entry_get_request__field_descriptors[3] =
{
  {
    "index",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TableEntryGetRequest, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "table_name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TableEntryGetRequest, table_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(TableEntryGetRequest, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned table_entry_get_request__field_indices_by_name[] = {
  0,   /* field[0] = index */
  2,   /* field[2] = key */
  1,   /* field[1] = table_name */
};
static const ProtobufCIntRange table_entry_get_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor table_entry_get_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TableEntryGetRequest",
  "TableEntryGetRequest",
  "TableEntryGetRequest",
  "",
  sizeof(TableEntryGetRequest),
  3,
  table_entry_get_request__field_descriptors,
  table_entry_get_request__field_indices_by_name,
  1,  table_entry_get_request__number_ranges,
  (ProtobufCMessageInit) table_entry_get_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor table_entry_get_reply__field_descriptors[3] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(TableEntryGetReply, status),
    &table_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(TableEntryGetReply, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(TableEntryGetReply, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned table_entry_get_reply__field_indices_by_name[] = {
  1,   /* field[1] = key */
  0,   /* field[0] = status */
  2,   /* field[2] = value */
};
static const ProtobufCIntRange table_entry_get_reply__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor table_entry_get_reply__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TableEntryGetReply",
  "TableEntryGetReply",
  "TableEntryGetReply",
  "",
  sizeof(TableEntryGetReply),
  3,
  table_entry_get_reply__field_descriptors,
  table_entry_get_reply__field_indices_by_name,
  1,  table_entry_get_reply__number_ranges,
  (ProtobufCMessageInit) table_entry_get_reply__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor table_entry_insert_request__field_descriptors[4] =
{
  {
    "index",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TableEntryInsertRequest, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "table_name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TableEntryInsertRequest, table_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(TableEntryInsertRequest, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(TableEntryInsertRequest, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned table_entry_insert_request__field_indices_by_name[] = {
  0,   /* field[0] = index */
  2,   /* field[2] = key */
  1,   /* field[1] = table_name */
  3,   /* field[3] = value */
};
static const ProtobufCIntRange table_entry_insert_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor table_entry_insert_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TableEntryInsertRequest",
  "TableEntryInsertRequest",
  "TableEntryInsertRequest",
  "",
  sizeof(TableEntryInsertRequest),
  4,
  table_entry_insert_request__field_descriptors,
  table_entry_insert_request__field_indices_by_name,
  1,  table_entry_insert_request__number_ranges,
  (ProtobufCMessageInit) table_entry_insert_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor table_entry_insert_reply__field_descriptors[1] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(TableEntryInsertReply, status),
    &table_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned table_entry_insert_reply__field_indices_by_name[] = {
  0,   /* field[0] = status */
};
static const ProtobufCIntRange table_entry_insert_reply__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor table_entry_insert_reply__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TableEntryInsertReply",
  "TableEntryInsertReply",
  "TableEntryInsertReply",
  "",
  sizeof(TableEntryInsertReply),
  1,
  table_entry_insert_reply__field_descriptors,
  table_entry_insert_reply__field_indices_by_name,
  1,  table_entry_insert_reply__number_ranges,
  (ProtobufCMessageInit) table_entry_insert_reply__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor table_entry_delete_request__field_descriptors[3] =
{
  {
    "index",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TableEntryDeleteRequest, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "table_name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TableEntryDeleteRequest, table_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(TableEntryDeleteRequest, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned table_entry_delete_request__field_indices_by_name[] = {
  0,   /* field[0] = index */
  2,   /* field[2] = key */
  1,   /* field[1] = table_name */
};
static const ProtobufCIntRange table_entry_delete_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor table_entry_delete_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TableEntryDeleteRequest",
  "TableEntryDeleteRequest",
  "TableEntryDeleteRequest",
  "",
  sizeof(TableEntryDeleteRequest),
  3,
  table_entry_delete_request__field_descriptors,
  table_entry_delete_request__field_indices_by_name,
  1,  table_entry_delete_request__number_ranges,
  (ProtobufCMessageInit) table_entry_delete_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor table_entry_delete_reply__field_descriptors[1] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(TableEntryDeleteReply, status),
    &table_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned table_entry_delete_reply__field_indices_by_name[] = {
  0,   /* field[0] = status */
};
static const ProtobufCIntRange table_entry_delete_reply__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor table_entry_delete_reply__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TableEntryDeleteReply",
  "TableEntryDeleteReply",
  "TableEntryDeleteReply",
  "",
  sizeof(TableEntryDeleteReply),
  1,
  table_entry_delete_reply__field_descriptors,
  table_entry_delete_reply__field_indices_by_name,
  1,  table_entry_delete_reply__number_ranges,
  (ProtobufCMessageInit) table_entry_delete_reply__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue table_status__enum_values_by_number[4] =
{
  { "SUCCESS", "TABLE_STATUS__SUCCESS", 0 },
  { "STAGE_NOT_FOUND", "TABLE_STATUS__STAGE_NOT_FOUND", 1 },
  { "TABLE_NOT_FOUND", "TABLE_STATUS__TABLE_NOT_FOUND", 2 },
  { "ENTRY_NOT_FOUND", "TABLE_STATUS__ENTRY_NOT_FOUND", 3 },
};
static const ProtobufCIntRange table_status__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex table_status__enum_values_by_name[4] =
{
  { "ENTRY_NOT_FOUND", 3 },
  { "STAGE_NOT_FOUND", 1 },
  { "SUCCESS", 0 },
  { "TABLE_NOT_FOUND", 2 },
};
const ProtobufCEnumDescriptor table_status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "TableStatus",
  "TableStatus",
  "TableStatus",
  "",
  4,
  table_status__enum_values_by_number,
  4,
  table_status__enum_values_by_name,
  1,
  table_status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
